[project]
name = "reflex-map"
version = "0.0.1"
description = "Reflex custom component map"
readme = "README.md"
license = { text = "Apache-2.0" }
requires-python = ">=3.8"
authors = [{ name = "", email = "YOUREMAIL@domain.com" }]
keywords = ["reflex","reflex-custom-components"]

[tool.poetry]
name = "reflex-map"
version = "0.1.0"
description = ""
authors = ["Daniel Fink <danfink@mit.edu>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
reflex = "^0.5.8"
pandas = "^2.2.2"
plotly = "^5.24.0"


[build-system]
requires = ["setuptools", "wheel", "poetry-core"]
build-backend = "setuptools.build_meta"
#build-backend = "poetry.core.masonry.api"

[project.urls]

[project.optional-dependencies]
dev = ["build", "twine"]

[tool.setuptools.packages.find]
where = ["custom_components"]